# RPC Endpoints for Avalanche
rpc:
  avalanche_mainnet: "https://api.avax.network/ext/bc/C/rpc"
  avalanche_fuji: "https://api.avax-test.network/ext/bc/C/rpc"

# Protocol Addresses for Avalanche DeFi
protocols:
  aave_v3:
    lending_pool: "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
    pool_address: "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
  
  benqi:
    lending_pool: "0x5C0401e81Bc07Ca70fAD469b451682c0d747Ef1c"
    pool_address: "0x5C0401e81Bc07Ca70fAD469b451682c0d747Ef1c"
    
  trader_joe:
    router: "0x60aE616a2155Ee3d9A6854BaF16D6C5bE5b3b8E8"
    factory: "0x9Ad6C38BE94206cA50bb0d90783181662f0Cfa10"

# Risk Parameters
risk:
  min_confidence_score: 0.85
  max_exposure_per_vault: 0.2  # 20% of portfolio
  max_slippage: 0.005  # 0.5%
  min_apr_threshold: 0.05  # 5%

# LLM Settings
llm:
  model: "gpt-4o-mini"
  temperature: 0.1  # Deterministic responses
  max_tokens: 1000
  context_window: 4000

# Strategy Execution
execution:
  gas_multiplier: 1.2
  max_retries: 3
  confirmation_blocks: 2

# Providers
providers:
  defillama:
    protocol_slug: "avalanche"
    api_url: "https://api.llama.fi"

# Monitoring
monitoring:
  targets:
    - address: "0x794a61358D6845594F94dc1DB02A252b5b4814aD"  # Aave V3 pool
      time_window: 3600  # 1 hour
      threshold: 2.0
    - address: "0x5C0401e81Bc07Ca70fAD469b451682c0d747Ef1c"  # Benqi pool
      time_window: 3600
      threshold: 2.0
    - address: "0x9Ad6C38BE94206cA50bb0d90783181662f0Cfa10"  # Trader Joe factory
      time_window: 3600
      threshold: 2.0
    
