# RPC Endpoints
rpc:
  rootstock: "https://public-node.rsk.co"
  flow: "https://flow-mainnet.g.alchemy.com/v2/YOUR_KEY"

# Protocol Addresses
protocols:
  rootstock:
    lending_pool: "0x2bEE6167f91d10Db23252e03dE039dA6B9047D49"
    pool_address: "0x057835Ad21a177dbdd3090bB1CAE03EaCF78Fc6d"
  
  flow_strategy:
    vault_address: "0x..."  # Add Flow Strategy vault address
    rpc_url: "https://flow-mainnet.g.alchemy.com/v2/YOUR_KEY"
    
  kitty_punch:
    lending_pool: "0x..."  # Add KittyPunch lending pool address
    rpc_url: "https://flow-mainnet.g.alchemy.com/v2/YOUR_KEY"

# Risk Parameters
risk:
  min_confidence_score: 0.85
  max_exposure_per_vault: 0.2  # 20% of portfolio
  max_slippage: 0.005  # 0.5%
  min_apr_threshold: 0.05  # 5%

# LLM Settings
llm:
  model: "gpt-4o-mini"
  temperature: 0.1  # Deterministic responses
  max_tokens: 1000
  context_window: 4000

# Strategy Execution
execution:
  gas_multiplier: 1.2
  max_retries: 3
  confirmation_blocks: 2

# Providers
providers:
  defillama:
    protocol_slug: "rootstock"
  
  blockscout:
    api_url: "https://rootstock.blockscout.com/api/v2"

# Monitoring
monitoring:
  targets:
    - address: "0x2bEE6167f91d10Db23252e03dE039dA6B9047D49"  # Rootstock pool
      time_window: 3600  # 1 hour
      threshold: 2.0
    - address: "0xF92cC3B19C585EA71aDcC65138f151BD4d69363C"  # Flow Strategy vault
      time_window: 3600
      threshold: 2.0
    - address: "0x..."  # KittyPunch lending pool
      time_window: 3600
      threshold: 2.0
    
